# Generated by Django 5.2.7 on 2025-11-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deployment",
            name="branch",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
